### ISSUE TITLE
Angular Universal not working with angular material, giving this issue.

### ISSUE THREAD

**Issue by sahil-developer-88** [evertonrobertoauler/cli-universal-demo#24]
at Array.filter (native)
    at new MdInputDirective (I:\cli-universal-demo-master---\dist\server.js:15493:11)
    at createClass (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:11038:26)
    at createDirectiveInstance (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:10863:37)
    at createViewNodes (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:12291:49)
    at Object.createEmbeddedView (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:12174:5)
    at TemplateRef_.createEmbeddedView (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:10378:38
)
    at ViewContainerRef_.createEmbeddedView (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:101
61:52)
    at NgIf._updateView (I:\cli-universal-demo-master---\node_modules\@angular\common\bundles\common.umd.js:1952:45)
    at NgIf.set [as ngIf] (I:\cli-universal-demo-master---\node_modules\@angular\common\bundles\common.umd.js:1911:18)
    at updateProp (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:11221:37)
    at checkAndUpdateDirectiveInline (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:10913:19)
    at checkAndUpdateNodeInline (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:12443:17)
    at checkAndUpdateNode (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:12382:16)
    at prodCheckAndUpdateNode (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:13074:5)
    at Object.updateDirectives (I:\cli-universal-demo-master---\dist\server.js:28381:9)
    at Object.updateDirectives (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:12831:72)
    at checkAndUpdateView (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:12349:14)
    at callViewAction (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:12712:21)
    at execComponentViewsAction (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:12644:13)
ERROR ReferenceError: document is not defined
    at getSupportedInputTypes (I:\cli-universal-demo-master---\dist\server.js:1308:60)
    at I:\cli-universal-demo-master---\dist\server.js:15493:40
    at Array.filter (native)
    at new MdInputDirective (I:\cli-universal-demo-master---\dist\server.js:15493:11)
    at createClass (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:11038:26)
    at createDirectiveInstance (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:10863:37)
    at createViewNodes (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:12291:49)
    at Object.createEmbeddedView (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:12174:5)
    at TemplateRef_.createEmbeddedView (I:\cli-universal-demo-master---\node_modules\@angular\core\bundles\core.umd.js:10378:38
)

It is giving this issue during build time (npm start). My whole of project is stuck by this issue. Any help would be highly appreciated.

**Comment by evertonrobertoauler** [comment]
Unfortunately the Angular Material does not support Server Side Rendering (their code is not isomorphic), follow this issue:
https://github.com/angular/material2/issues/308
