### ISSUE TITLE
TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by iUwej** [evertonrobertoauler/cli-universal-demo#33]
I have adapted a project by angular/cli to use server side rendering as per you example but am getting this error on making a request
`listening on http://localhost:3000!
TypeError: Cannot read property 'create' of undefined
    at /Users/suiluj/projects/design-portal-frontend/node_modules/@angular/core/bundles/core.umd.js:4529:60
    at ZoneDelegate.invoke (/Users/suiluj/projects/design-portal-frontend/node_modules/zone.js/dist/zone-node.js:392:26)
    at Object.onInvoke (/Users/suiluj/projects/design-portal-frontend/node_modules/@angular/core/bundles/core.umd.js:3922:33)
    at ZoneDelegate.invoke (/Users/suiluj/projects/design-portal-frontend/node_modules/zone.js/dist/zone-node.js:391:32)
    at Zone.run (/Users/suiluj/projects/design-portal-frontend/node_modules/zone.js/dist/zone-node.js:142:43)
    at NgZone.run (/Users/suiluj/projects/design-portal-frontend/node_modules/@angular/core/bundles/core.umd.js:3853:69)
    at PlatformRef_._bootstrapModuleFactoryWithZone (/Users/suiluj/projects/design-portal-frontend/node_modules/@angular/core/bundles/core.umd.js:4527:23)
    at PlatformRef_.bootstrapModuleFactory (/Users/suiluj/projects/design-portal-frontend/node_modules/@angular/core/bundles/core.umd.js:4509:21)
    at Object.renderModuleFactory (/Users/suiluj/projects/design-portal-frontend/node_modules/@angular/platform-server/bundles/platform-server.umd.js:2405:39)
    at View.engine (/Users/suiluj/projects/design-portal-frontend/dist/server.js:850:23)`

What could have gone wrong in my set up?

**Comment by iUwej** [comment]
After logging, found out the AppServerModuleNgFactory is not created during the build. Still can't figure out why

**Comment by iUwej** [comment]
Had to compile in --aot mode
